### ISSUE TITLE
css-like theme classes assignable to UI elements

### ISSUE THREAD

**Issue by ylenard** [MyreMylar/pygame_gui#117]
**Is your feature request related to a problem? Please describe.**
Currently I have to describe the theme for each element individually(using prototypes) or using the class / default descriptor. In a GUI with large amount of differently themed widgets it gets cumbersome.

**Describe the solution you'd like**
I'd like to be able to assign multiple theme css-like "classes" directly to a UI element. 

**Describe alternatives you've considered**
The same could be achieved by allowing multiple prototypes and using them to style the element with an individual theme (via object_id), but it would require an unnecessary step.

This may be a bad place to ask, but it is somewhat related - is it intentional that multiple UI elements can have the same object_id?

**Comment by MyreMylar** [comment]
Had a start on implementing this, but would like to hear feedback in case I'm doing it all wrong.

**Comment by ylenard** [comment]
It seems good to me.
The only thing I see that you could perhaps think about is the naming - since it's possible to pass both an id of the object and of the class perhaps the parameter and the named tuple would be better called something like theming id to avoid confusion?

**Comment by MyreMylar** [comment]
I did think about that, but it would break the code of anyone using the current 'object_id' parameter as a keyword, so I thought I'd leave it for compatibility reasons.

**Comment by ylenard** [comment]
You could always add a new parameter, but keep object_id as is to preserve compatibility. A deprecation warning should be enough to make people switch over to the new one, so that object_id could be removed in some future version..

**Comment by MyreMylar** [comment]
Been pondering this again today (while doing the washing up).

It's quite tricky to manage deprecation of keyword parameters in python - especially the way I began with this project where parameters are, in the vast majority, optionally keyword or positional. If I add a new one on the end with a new name, and then later remove one from further up the order then the very act of removing one will also affect everyone using positional parameters to create elements and not in an immediately obvious way.

The other difficulty is that the IDs are used mostly for theming, but also optionally for events (because it seemed pointless having two types of object ID) so naming them theming IDs doesn't cover their dual role in the GUI.

**Comment by ylenard** [comment]
I have to say I haven't thought about it this way - I guess deprecation is harder to handle than I thought. Now I understand why they added keyword only arguments in Python 3.8.

**Comment by MyreMylar** [comment]
Yep, I'm hoping to start using them more in the future for option type stuff - though I think they are actually valid in all versions of python 3? Just not Python 2.
