### ISSUE TITLE
Allow assigning of theme files to a UI element

### ISSUE THREAD

**Issue by ylenard** [MyreMylar/pygame_gui#118]
**Is your feature request related to a problem? Please describe.**
It becomes hard to manage themes when there are a lot of differently styled UI elements in the same view. 
My case:
I have a gameplay gamestate with a lot of UI elements. I'd like to create an ingame menu consisting of a panel and children buttons. Currently I have to add their themes to a theme file that already contains over a thousand lines. 

**Describe the solution you'd like**
I'd like to be able set a theme file to a UI element. The theme should apply to the element and its children. The hierarchy of themes should be: Element theme file>Parent theme file>...>UI manager theme file.
In my case this would allow me to create a theme specifically for my ingame menu, and simply set "panel" and "button" element themes in it. It would also allow me to split themes for other widgets from my main theme file massively improving readability.

**Describe alternatives you've considered**
Could also be somewhat implemented in a much simpler way - allow assigning of multiple theme files to a single UI manager. This way, in my case, I would also be able to split the ingame menu themes off from the main theme file, but it would require me to still set the styling by object_id.

**Comment by MyreMylar** [comment]
I wonder if the multiple theme files thing might already work unintentionally. If you:

    ui_manager.get_theme().load_theme('theme_file_2.json')
    ui_manager.get_theme().load_theme('theme_file_3.json')
    ui_manager.get_theme().load_theme('theme_file_4.json')

I feel like it might just work. Mainly because at the moment the default theme is already loaded first every time anyway.

**Comment by ylenard** [comment]
Unintentional or not - it seems to work! 

So the theme keeps adding additional data when loading new files. I was sure it would replace it and didn't check. I'd call that a feature :)

**Comment by MyreMylar** [comment]
I also added some documentation on using multiple theme files to the class ID PR.

I think with multiple theme files, class IDs and prototypes it should be possible to get theme files down to a manageable size now - without potentially loading one per element. 

I think I'd like to steer people away from that in general, purely because of data loading concerns. It's generally easier to load one large file than many small ones and I'm sure the moment I added something that hinted at a file-per-object someone out there would create a grid of 1 pixel buttons that loaded 4,800 unique files and then ask me why it was slow.

**Comment by ylenard** [comment]
I think the theme file sizes are manageable now as well. I've split mine into several files and it was enough for now - I have a separate theme file for every group of UIElements (menu, widget, submenu).

The only thing right now is that all the themes are stored in the UIManager all the time - even when they aren't used, but I think the memory cost should be miniscule and not worth caring about.
