### ISSUE TITLE
Concurrently running windows

### ISSUE THREAD

**Issue by karx1** [MyreMylar/pygame_gui#141]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Windows are all run in one thread, which makes big programs very slow and sometimes unresponsive

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Proper support and documentation for using threading or asyncio to load windows

**Comment by karx1** [comment]
I want to be able to initialize my custom window class in a function, so maybe I could run that function in a thread? What I want to know is whether pygame_gui still functions normally in a separate thread.

**Comment by MyreMylar** [comment]
I doubt you'll get much out of multi-threading the GUI in that way. For one - python is bad at threading in general still (especially if you need to support older versions of python), for two SDL (which pygame uses) is not great at it either - for three, running windows in separate threads is not generally a classic multi-threading situation. 

Or at least I've not seen it much, usually you want to split off something very mathy where the CPUs can run off and do stuff on their own without having to involve graphics and memory or something where you kick a bunch of work off while waiting on hardware to get back to you . UI is pretty much all graphics and moving stuff in and out of memory in a specific order. 

I expect if you try it you might get some SDL errors in the event system and when you try and draw things - though what exactly happens might depend on your version of pygame/SDL, what platform you are on and your python version - as all that stuff seems to be very much in flux. Another reason I haven't delved that deeply into it as I have to support many older versions of python and SDL.

You can read the SDL thread information here:
https://wiki.libsdl.org/CategoryThread

Particularly:

>  NOTE: You should not expect to be able to create a window, render, or receive events on any thread other than the main one.

The library does already use multiple threads for loading data, mostly because it seemed to be more well established as a concurrency solution, avoids SDL problems - and it made a reasonable performance difference there when opening a bunch of files.

Are you experienced in writing multi-threaded code yourself? I wouldn't class myself as much of an expert so take what I say with a pinch of salt. 

Also, if you are having performance problems in general, perhaps explain what you are trying to do or link your code somewhere - it's possible that there are non-concurrency things that might improve it, or perhaps you just need to think about concurrency in your code in a different way? Not that I am the concurrency wizard or anything.

**Comment by MyreMylar** [comment]
See also this issue about drawing things in a different way to maybe speed up drawing at the cost of more memory usage:

https://github.com/MyreMylar/pygame_gui/issues/95

**Comment by karx1** [comment]
Alright, thanks. I'm helping develop [snakeware](https://github.com/joshiemoore/snakeware), and we'd like to have things running concurrently instead of running everything under one python instance. Looks like we can't though, so I'm closing the issue.
