### ISSUE TITLE
An Example for UIVerticalScrollBar

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#149]
**Is your feature request related to a problem? Please describe.**
I've followed the docs and now have a scroll bar showing in the window but whilst it moves up and down in response to the mouse it doesnt change the internal areas visibility/position.

**Describe the solution you'd like**
An example in the examples repo that shows how to use the vertical scroll bar to display information held in a container that exceeds the size of the outer container.  e.g. some UITextBox's inside a UIWindow. 

**Describe alternatives you've considered**
Copying the code from the UITextBox into the UIWindow class. Having the UIWindow automatically add the scrollbar, like the UITextBox, when the contained content exceeds its size, would be ideal. 

**Additional context**
https://i.imgur.com/NnlrHpj.png

**Comment by MyreMylar** [comment]
There are two slightly different examples for this sort of thing at the minute:

1. Is just the message box window which shows how to stick a single text box inside of a UI window. This one is just for text.
2. Is the [UICanvasWindow ](https://github.com/MyreMylar/pygame_paint/blob/master/ui/ui_canvas_window.py) in the Pygame Paint project which uses the [UIScrollingContainer ](https://github.com/MyreMylar/pygame_gui/blob/main/pygame_gui/elements/ui_scrolling_container.py). With it you can have any UI element in a vertical and/or horizontal scrolling area. This project doesn't work particularly well in pygame 2 at the minute, but that's not because of the scrolling area.

Basically as you've discovered the scroll bar on it's own is not enough, you need to connect it to an area to scroll which can get quite complicated which is why I have built it in automatically to the text box and to the scrolling container. I would guess that you should be able to stick multiple scrolling or non-scrolling text boxes inside of a scrolling container, though I haven't built out UIs that are that complicated yet myself. 

For various reasons automatically changing the size of the scrolling area based on the contents isn't always desirable but I suspect there will eventually be a variant of the scrolling container, or an option, that enables a more limited scrolling container that does expand to the right and left if things are placed outside of it's boundaries. Though changing the scrollable area yourself is not that hard. see:

```
self.scrolling_container.set_scrollable_area_dimensions((new_width, new_height))
```

**Comment by Snayff** [comment]
Ah, I didn't see scrolling container. That might be all that's needed. I
might have missed it in the examples folder and docs - sorry about that!
