### ISSUE TITLE
Option to Override UIWindow Close Button

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#150]
**Is your feature request related to a problem? Please describe.**
When click the close button on a `UIWindow` I dont necessarily want to kill it and I often have other actions I need to run at the same time. 

**Describe the solution you'd like**
Let us override the function used by the close button. By default this could just be a wrapper for `.kill()`, which is what is used now.

**Comment by Snayff** [comment]
I havent made a pull request before but I think I can add this pretty easily.  I clicked around but I must be missing something. Do I need to fork the repo?

My thinking is to replace `self.kill()` on ui_window.py:235 with a call to a method and have that method call `self.kill()`.

**Comment by MyreMylar** [comment]
For things that happen at the same time as closing the window the general solution for this is this event:

https://pygame-gui.readthedocs.io/en/latest/events.html#uiwindow-ui-window-close

Why would you not want the close button to close the window though? You can of course do whatever you want with your own windows by overriding them - is this just because the UI doesn't have something like a minimise button? 

I don't think there is any particular need to insert another method other than `kill()` for a window by default as for windows it basically _is_ the method you call when you press the close window button. Normally when I press the close window button in a UI I expect it to try and close the window so I think it makes sense to keep that as the simple default. I would just override `kill()` for your odd custom window and, if you need another method for your custom window to actually close the window, make that instead and call it from your alternative route to actually close the window.

**Comment by Snayff** [comment]
I could use the event created when it closes but by that point the menu is
killed so my options are more limited. You're right though, this is mostly
to allow me to effectively minimise the window. I've pointed my close
button at the hide method and then fire a custom event to allow me to
change state and update my info related to the menu.

The reason I haven't tried to override kill is because when I want the menu
to be deleted entirely I still want to call that method.

Hope that makes sense. If you don't think the abstraction of the close
button method is needed then happy to close the request.

**Comment by MyreMylar** [comment]
I would just add a function to your custom window called 'actually_kill()' that is a copy of the current `kill()` and then use that one when you want to actually kill the window. 

I'll try and come up with some good way to support a minimize button for windows next time I give them a once over - I think there is an issue for it already somewhere, or at least there was some chat about it. It may just have to be an optional title bar button that hides a window and creates an event saying it did so because there is not a good way to integrate 'unminimize' functionality into a window without bundling up other assumptions into how people might want to use windows.

**Comment by yanickrochon** [comment]
I believe that this issue has been overlooked. I too believe that killing the window may not be desired. For example, my UI creates the entire layout and has components to show and hides windows. When the user closes the window, I would rather have it hidden instead of killed.

There should be an option for this and I propose this solution 

```python
pygame_gui.elements.UIWindow(
    rect=pygame.Rect(( x, y ), ( w, h )),
    window_display_title="Some title",
    resizable=True,
    visible=False,          # initial visibility
    close_action="hide"     # or "kill"
    manager=manager
)
```
These close actions could be in contants, for example : `pygame_ui.elements.WINDOW_KILL` and `pygame_ui.elements.WINDOW_HIDE`

**Comment by MyreMylar** [comment]
I've just now added in my dev branch (meaning it will be in 0.6.0) a simple wrapper function called: `on_close_window_button_pressed()` which by default calls `self.kill()`. That way anyone who wants their windows to hide instead can just override this method in their window class like so:

```
class MyHidingWindow(UIWindow):
    def on_close_window_button_pressed(self):
        self.hide()
```

At this point I'm generally trying to avoid adding more stuff into the element constructors as they are already quite large and complex and I want the introductory interface to be as simple as possible.

You can already remove the close window button for a window in the theme file. It's the misc option `enable_close_button` - see:

https://pygame-gui.readthedocs.io/en/latest/theme_reference/theme_window.html#theme-window
