### ISSUE TITLE
Get relative mouse co-ordinates for individual windows

### ISSUE THREAD

**Issue by Cyppa** [MyreMylar/pygame_gui#154]
So sorry if this is already solved but I can't seem to find in the documentation how to get relative mouse co-ordinates for the window that is being used. Pygame gives me absolute mouse co-ordinates  which I can use in pygame_gui but if I have a pygame_gui window within another pygame_gui window is there ways to get relative mouse co-ordinates of the smaller inner window? If I press the bar at the top of the inner window this mouse click acts differently for some reasons and pygame doesn't give me a buutondown event. Does pygame_gui have its own way to get mouse coordinates?

**Comment by MyreMylar** [comment]
So far - no, though it's likely a convenience function that could be added to the window class fairly easily with a bit of math.

I guess most people would probably want co-ordinates relative to the top left corner of the window contents rather than the whole element (which includes the window shadow and the title bar) - that's how pygame does it anyway.

I'll add it to my to do list.

In the short term you could likely grab the absolute mouse position from pygame and subtract the top left corner of the contents container for the window you are interested in.  Should be something like:


```
abs_mouse_pos = pygame.mouse.get_pos()
window_contents_top_left = my_window.get_container().get_rect().topleft
rel_mouse_pos = (abs_mouse_pos[0] - window_contents_top_left[0],
                 abs_mouse_pos[1] - window_contents_top_left[1])
```

Though that is just me scribbling code on the back of a business card after a long summer holiday so take it with a pinch of salt.

**Comment by Cyppa** [comment]
Thanks for the reply. I ended up finding out another way but it a lot more convoluted than what you wrote. I'll give your idea a go. Thanks again.

**Comment by MyreMylar** [comment]
I'm adding `get_relative_mouse_pos()` to the UIWindow class in 0.6.0. This will give you a mouse position relative to the contents of a UI Window (so not including the title bar).
