### ISSUE TITLE
Is it pygame_gui or pygame-gui?

### ISSUE THREAD

**Issue by Farbfetzen** [MyreMylar/pygame_gui#156]
Both pygame_gui and pygame-gui seem to install fine using the terminal. However, PyCharm lists the package only as "pygame-gui". I find this confusing. Is this a quirk of pip and can be ignored? Maybe it should be mentioned in the readme.

**Comment by MyreMylar** [comment]
Yeah, this is a fairly hidden package rule that any non alphanumeric characters in package names get silently converted to dashes, so even though I originally called it `pygame_gui`, on the PyPI servers (which PyCharm uses to get the list), it will exist as `pygame-gui`.  The good news is that it seems to work both ways so if you try `pip install pygame_gui` it converts it to `pip install pygame-gui` so most of the time it shouldn't matter, but it has confused me on occasion.

I guess I should probably rename everything to use the `pygame-gui` standard at some point anyway so this issue can serve as the reminder. Thank you.

**Comment by BastiHz** [comment]
Thank you for your explanation. I was also somewhat worried because PyPI had some cases of typosquatting in the past. I'm relieved to know that both names refer to the same package.

**Comment by MyreMylar** [comment]
Got around to investigating this today. It turns out that you actually can't name packages with a dash in the middle at all (python can't import them). There is some lengthy complicated reason to do with search engine optimisation why PyPI turns packages with underscores into dashes.

The TLDR answer is, I can't easily rename the package now as `pygamegui` is taken and `pygame-gui` is not legal python. I think in the future I will avoid all non-lowercase letters in package names to save the confusion.

For now things will remain:

- pygame-gui for PyPI listings (pip will accept pygame-gui or pygame_gui).
- pygame_gui for python programming.

Incidentally you can have an entirely different name imported in python to the name on PyPI but that is probably just more confusing.

I'll close this out by adding a note to the main page of the docs I think.
