### ISSUE TITLE
Allow loading theme by string/dict.

### ISSUE THREAD

**Issue by glipR** [MyreMylar/pygame_gui#182]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to change the font and background colour of some dynamically generated buttons.
Because I want these attributes to be dynamic (IE not defined in a theme file), the only way I've found to achieve this is with the following:

```python3
data = {}
# Here, i is the index of the button being generated.
but = pygame_gui.elements.UIButton(
    relative_rect=pygame.Rect(button_left, button_top_orig + button_top_inc * i, *button_size), 
    text=entry[0], 
    manager=self,
    object_id=pygame_gui.core.ObjectID(f"color-button-{i}")
)
col = genCol(i)
data[f"color-button-{i}"] = {
    "colours": {
        "normal_bg": col,
        "hovered_bg": col,
        "active_bg": col,
    },
    "font": {
        "name": "Poppins",
        "size": "24",
        "regular_resource": {
            "package": "<package-path>",
            "resource": "Poppins-Regular.ttf"
        }
    },
    "misc": {
        "border_width": "4"
    }
}
self.ui_theme._load_element_colour_data_from_theme("colours", f"color-button-{i}", data)
self.ui_theme._load_element_font_data_from_theme("font", f"color-button-{i}", data)
self.ui_theme._load_element_misc_data_from_theme("misc", f"color-button-{i}", data)
self.ui_theme._load_fonts()
but.rebuild_from_changed_theme_data()
```

Which is likely to fail in later versions and probably unsafe.

**Describe the solution you'd like**
Move the contents of `UIAppearanceTheme.load_theme` so that after `json.load` is called, we delegate to a new function, `load_theme_from_obj(self, obj: dict)`.

**Describe alternatives you've considered**
If there's a nice way to change the button attributes without digging into themes then this is great too!

**Additional context**
Thanks for the great library =)

**Comment by glipR** [comment]
I should add, if this change was made then I could simply do:

```python3
data = {}
# Here, i is the index of the button being generated.
but = pygame_gui.elements.UIButton(
    relative_rect=pygame.Rect(button_left, button_top_orig + button_top_inc * i, *button_size), 
    text=entry[0], 
    manager=self,
    object_id=pygame_gui.core.ObjectID(f"color-button-{i}")
)
col = genCol(i)
data[f"color-button-{i}"] = {
    "colours": {
        "normal_bg": col,
        "hovered_bg": col,
        "active_bg": col,
    },
    "font": {
        "name": "Poppins",
        "size": "24",
        "regular_resource": {
            "package": "<package-path>",
            "resource": "Poppins-Regular.ttf"
        }
    },
    "misc": {
        "border_width": "4"
    }
}
# MODIFIED: No hidden function calls.
self.ui_theme.load_theme_from_obj(data)
# END MODIFIED REGION
but.rebuild_from_changed_theme_data()
```

**Comment by MyreMylar** [comment]
If you just wanted to do this with button colours then the easiest way right now is likely to:

1. - Create the button.
2. - Edit the buttons colour dictionary to your dynamic colours.
3. - Call `rebuild()` on the button.

Like so:

```
but = UIButton(
                relative_rect=pygame.Rect(button_left, button_top_orig + button_top_inc * i, *button_size), 
                text=entry[0], 
                manager=self)

# generate some dynamic colours
col = genCol(i)

but.colours["normal_bg"] = col
but.colours["hovered_bg"] = col
but.colours["active_bg"] = col

but.rebuild()
```

Fonts are a little trickier - I'm actually switching over the underlying font object used in the upcoming version, and you might also want to turn off the UIManager feature that does auto-updating of UIElements when the theme file is changed.

In general with fonts you want to pre-load at the start all the different font styles you are going to use in your game/app because there is a noticeable lag each time you load a new font instance into memory. That means font sizes, styles (bold, italic, regular) and 'face' (i.e. which font file) should ideally be defined up front and then used later on. So for dynamically generated buttons that need to have different fonts, I would suggest picking from a range of already preloaded fonts.

That's a digression though, I think your idea of splitting the json loading up in this way also has merits and no doubt someone else will find it useful too. I'll add it it to the TODO list.
