### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by t0a5ted** [MyreMylar/pygame_gui#188]
Is this project discontinued? There hasnt been a commit in 3-4 months, and ive been waiting for a new version.

**Comment by MyreMylar** [comment]
Nope, not discontinued - there is a more active version 6 branch over here:

https://github.com/MyreMylar/pygame_gui/tree/version_060

but, yes progress has been still slow because it's just me working on it, and the pandemic ramped the hell up over here in the UK and I got drafted into a bunch of pandemic response stuff that has taken up all my normal coding time.

Was there a particular feature you were waiting on?

**Comment by t0a5ted** [comment]
oh okay... thats understandable and i hope you're doing well in these tough times.

**Comment by MyreMylar** [comment]
Thanks :)

Trying to sneak in a bit of coding here and there around work.
