### ISSUE TITLE
Failing to amend Themes.json

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#190]
Pygame_gui allows us to change a value in the json by hand and have that immediately reflected in the game. To be able to set the images on buttons for a skill bar I am trying to do the same thing via code. With the code already in place to handle a change to the themes.json I thought it best to amend that, however I just saw #182 so I am thinking that might be a better approach.

This is what I have so far. It seems to work, in so far as the json changes, but it breaks the library. 

Am I doing it wrong or is it not compatible with pygame_gui?

```python
def set_skill_image(self, skill_number: int, image_path: str):
    """
    Set the image for the skill
    """
    str_path = str(UI_PATH / "themes.json")

    # prepend assets/ as skills.json doesnt include it but themes.json needs it
    if image_path != "":
        _image_path = "assets/" + image_path
    else:
        _image_path = image_path

    # open the file
    with open(str_path, "r+") as file:
        data = json.load(file)

        # edit data
        data[f"skill_{skill_number}"]["images"]["normal_image"]["path"] = _image_path
        data[f"skill_{skill_number}"]["images"]["hovered_image"]["path"] = _image_path

        # reset file position
        file.seek(0)

        # save changes
        json.dump(data, file, indent=4)

        # remove remaining part
        file.truncate()
 ```

Error received:
```python
  File "C:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\notquiteparadise-xJWCttl6-py3.8\lib\site-packages\pygame_gui\ui_manager.py", line 234, in update
    if self.ui_theme.check_need_to_reload():
  File "C:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\notquiteparadise-xJWCttl6-py3.8\lib\site-packages\pygame_gui\core\ui_appearance_theme.py", line 152, in check_need_to_reload
    self.reload_theming()
  File "C:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\notquiteparadise-xJWCttl6-py3.8\lib\site-packages\pygame_gui\core\ui_appearance_theme.py", line 175, in reload_theming
    self.load_theme(self._theme_file_path)
  File "C:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\notquiteparadise-xJWCttl6-py3.8\lib\site-packages\pygame_gui\core\ui_appearance_theme.py", line 705, in load_theme
    self._load_images()
  File "C:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\notquiteparadise-xJWCttl6-py3.8\lib\site-packages\pygame_gui\core\ui_appearance_theme.py", line 277, in _load_images
    self._resource_loader.add_resource(image_resource)
  File "C:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\notquiteparadise-xJWCttl6-py3.8\lib\site-packages\pygame_gui\core\resource_loaders.py", line 105, in add_resource
    raise ValueError('Too late to add this resource to the loader')
ValueError: Too late to add this resource to the loader
Avg FPS: 53.74, R_Avg: 50.91

Process finished with exit code -1
```

**Comment by MyreMylar** [comment]
Generally pygame gui tries to help users out by encouraging them to do all the necessary loading of UI data at the start of the app.

For something like UI button images in a fairly simple game I would usually encourage them all to be loaded at the start, rather than dynamically during the apps run-time. This just helps divide your app into clear phases of 'loading' and 'running' and the loading phase can potentially benefit from threading. The point of the dynamic editing of theme files is really for the game developer to be able to tweak stuff in the UI while the app is running, as a development tool. Its not so much for them to use code to append lines onto the file to dynamically load images as part of the normal running of the application. To me this looks a bit like somebody took the stethoscope and thermometer from a doctor and just sewed them right into the patient :)

Having said that, there is a bug here. The loading is supposed to swap back from threaded loading to simple loading for everything after the initial system load and it does for fonts, but not for images. I think I just fixed it locally so this she make it into 0.6.0. Also, I don't really know your app plans, and you are, of course, free to use pygame_gui however you like - just be aware that I may not have envisaged all of your applications in my original designs.

I expect there will be various other changes to image loading & handling in the future.

**Comment by Snayff** [comment]
Thanks for coming back to me, mate. 

I totally appreciate that your design intent is what will inform how pygame_gui develops, I would rather use it as intended than fight against it. 

That said, I think there would be value in being able to have 1 button type and then specify the element that changes in code. For example, say I have 50 skills; all skill buttons function and look the same, with the exception that the icon shown will be different for each skill. Currently, I could `.set_text` on each button to add the name of the skill, but to show the icon I would need 50+ blocks in the theme, right?

I tried the approach you mentioned in  #145 but the results arent quite what I expected; the text is hidden behind the text and the image disappears on hover. 
```
button.drawable_shape.states["normal"].surface.blit(surface, (0, 0))
button.drawable_shape.states["normal"].has_fresh_surface = True
button.drawable_shape.states["hovered"].surface.blit(surface, (0, 0))
button.drawable_shape.states["hovered"].has_fresh_surface = True
```
Of course, its all somewhat moot if I am breaking pygame_gui to do something it doesnt want to do! 😄

**Comment by Snayff** [comment]
Not sure if this will come back to bite me but doing this for the a button when I want to add a new image seems to work:
```python
button.normal_image = surface
button.hovered_image = surface
button.selected_image = surface
button.rebuild()
```
