### ISSUE TITLE
UI Pygame window

### ISSUE THREAD

**Issue by donno2048** [MyreMylar/pygame_gui#194]
A window for pygame_gui, but you can give it a display argument (or something else), and having a pygame window run inside another pygame window. This would be awesome, I sometimes find myself rewriting pygame applications to fit them inside bigger apps and that's not so fun.

**Comment by MyreMylar** [comment]
I think you can basically do this already as much as I would want to support? You just make your pygame game as normal, except instead of opening a pygame window (beyon the one you already have open to run pygam _gui), you open a pygame_gui window and blit your final game surface to that instead of the pygame window display surface.

 See the 'windowed_mini_games.py' file in the examples project, the first screenshot down shows roughly what it looks like:

https://github.com/MyreMylar/pygame_gui_examples

**Comment by donno2048** [comment]
I manage to fit my pygame app into a class to do that. Thanks!!!
