### ISSUE TITLE
Use default fonts on UIButtons using json theme files

### ISSUE THREAD

**Issue by Sunchock** [MyreMylar/pygame_gui#211]
**Is your feature request related to a problem? Please describe.**
Yeah, i would like to make a button and change its font by using JSON themes, but i cannot without download the ttf files. I have to precise where to find the file and I don't know where to get them in my OS for default system fonts.

**Describe the solution you'd like**
Based on the doc's configuration, why not to add a new option to tell pygame-gui to use a sysfont ?
`{
	"name": "segoeui",
	"size": "11",
	"bold": "0",
	"italic": "0",
	"sysfont": "1"
}`
and nothing more !

**Describe alternatives you've considered**
Maybe we can already do this by specify the font path in the default operating system or by another solution which i don't know for now

**Additional context**
I tryied searching for a solution on the web or in the project issues section but i didn't found any solution for now.

**Comment by MyreMylar** [comment]
Hello!

Currently the library doesn't use the SystemFonts submodule of pygame. It's had a few issues over the years with slow loading times (this could even effect apps where you didn't directly use the system fonts if care was not taken) and a rather sparse font selection which made me not want to include it by default.

I also haven't personally found it useful because:

a) It's not properly portable, different fonts are available on linux, windows & mac.
b) The way I work I tend to stick with a default font while developing until ready for custom font selection then I always grab whatever fonts I want to use from a place like [google fonts](https://fonts.google.com/) which is an actually usable font browser. Then I bundle the font files in with the app if I want to make it portable/compile it with PyInstaller.

If somebody wanted to patch in usage of the SystemFont module to the library in the future I wouldn't be opposed - this is an open source project and accepts pull requests, but it is not a priority for me personally.

**Comment by Sunchock** [comment]
Thanks you for your very clear and complete response !
I understand more now why we cannot do this, so in my case I consider my issue as 'resolved'
Following your advice, I downloaded a font then I encapsulated it in my project
