### ISSUE TITLE
Add an update_theming() to all elements

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#253]
A catch all way to support dynamic-in-code theming for those who want to alter the way elements look from within the code rather than via a theme file.

The idea is to follow the nested dictionary structure of the `.json` files we currently use for theming but just pass those theming blocks directly an element rather than the element having to go fetch them from the theme file.

**Proposed interface**

Updating a single colour for a button:
```
button.update_theming({'colours': {'normal_bg': '#FF0000'}})
```

**Implementation**

I think it's likely we can refactor the current `rebuild_from_changed_theme_data()` functions to branch based on going to the theme file or reacting to a passed in dictionary of theming blocks.

**Issues**

This won't work smoothly together with dynamic updating of UI themes from editing the theme file, but I doubt they are features that really have overlapping use cases.

Editing theme files and having that show up in a live demo is for programmers/designers tweaking UI appearance parameters, whereas dynamically changing an elements theming is probably for some in-game effect when you don't want to make a new element for whatever reason. 

My original design anticipated that users would be a lot more comfortable destroying and recreating elements when they wanted them to change, but it seems many users want to keep the same element objects around and change everything about them them with function calls instead.

**Comment by ConquerProgramming1** [comment]
Seems like a good idea -- separating data from whether it resides in a file or is provided dynamically is definitely best practice.

Additional opportunity here -- when doing the scrollbar work, I noticed we have a lot of duplicated theming code (setting up the same parameters for borders, or text), and it would be nice to factor those out so that standard theme items are set in one place. Doing this cleanly is probably a combination of object hierarchy -- subclasses setting their specific values then calling super() to add standard values -- and possibly separate methods for, say, text theming which not all classes use.

Also agree that people tend to want to change an existing element rather than recreate it. There is potentially a performance win there as well.

One other thought -- perhaps for theming (if not in general) have some flag that indicates whether we're in development or production mode, to handle stuff like updating if the theme file changes, which in production is just a waste of CPU.
