### ISSUE TITLE
set_dimension() after a set_image() of a UIImage display the initial surface

### ISSUE THREAD

**Issue by jlaumonier** [MyreMylar/pygame_gui#258]
**Describe the bug**
On a UIImage element initalized with dimension different from the surface dimension, calling set_dimension() with dimension different from the surface dimension after calling set_image() keep the initial image.

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialize UIImage with dimension different from the surface dimension
2. call `set_image()` with an other surface
3. call `set_dimension()` with dimension different from the surface dimension

**Expected behaviour**
The new surface should be displayed

**Screenshots**
N/A. 

**Platform and software (please complete the following information):**
 - OS: Linux (not tested on other)
 - Pygame GUI version 0.6.0
 - Pygame version 2.1.2

**Additional context**

See the following script that reproduces the problem. Probably the problem is due to the `original_image` attribute of UIImage which is not replaced by `set_image()` (of parent) but i am not sure of the best solution to correct it.

```
import pygame
import pygame_gui

pygame.init()

window_surface = pygame.display.set_mode((800, 600))

manager = pygame_gui.UIManager((800, 600))

imgX = pygame.image.load('X.png')  # 200x200 image
imgO = pygame.image.load('O.png')  # 200x200 image

img1 = pygame_gui.elements.UIImage(pygame.Rect((50, 50), (400, 400)),
                                   imgX,
                                   manager)
img1.set_image(imgO)  
img1.set_dimensions((400, 400))  # The 'X' image is displayed instead of "O"

clock = pygame.time.Clock()
is_running = True

while is_running:
    time_delta = clock.tick(60) / 1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False
        manager.process_events(event)
    manager.update(time_delta)
    manager.draw_ui(window_surface)
    pygame.display.update()
```

![X](https://user-images.githubusercontent.com/48807423/152619050-d3dad68d-34ec-4fe6-9c8b-bef413b83653.png)
![O](https://user-images.githubusercontent.com/48807423/152619109-a28f3e2c-f6ab-4e33-8aec-102398461a00.png)

**Comment by MyreMylar** [comment]
Yeah it has grown a bit confusing.

 `set_image()` right now is really an internal sort of function created to make sure the surface clipping is updated when any element's surface data is updated - because in pygame sprites surface data is attached to the `.image` attribute I've used that terminology for the element's surface data. This creates a bit of confusion for the `UIImage` element which pre-dates `set_image()` in the library as it seems like you should (reasonably) be able to change the image on it with `set_image()` much like many of the other elements now let let you change the text with `set_text()`.

The answer, for now, is to just recreate the `UIImage` element when you want to change the image - rather than calling `set_image()`. I expect eventually I'll change the current `set_image()` to have a less attractive name and maybe hide it behind an underscore as per python convention and then introduce a new `set_image()` just for the `UIImage` class that does what you would expect for this class (changing the .original_image and scaling it to the current dimensions).

**Comment by jlaumonier** [comment]
Ah ! ok, I understand. So, it's not a bug, it's a feature :) 
I did that to avoid the creation of a new object each time but i will refactor my code to take that into account. 
Thanks !
