### ISSUE TITLE
Fix RunTimeError: The pygame.freetype library isn't initialized when trying to create an instance of pygame_gui.ui_manager.UIManager()

### ISSUE THREAD

**Issue by samarth466** [MyreMylar/pygame_gui#269]
Hi, When creating an instance of the pygame_gui.ui_manager.UIManager() class, Python throws an error that reads "RunTimeError: The pygame.freetype library isn't initialized.". This bug is located in pygame_gui.core.utility on line 383. I took a look at the source code and found that in order to fix this bug, you have to add the following line on line 380.
pygame.freetype.init()
This function only has one parameter which is:
cache_size: int = 64
There are at least three places in that same file that have the same issue and can all be fixed at the same time by using this line. The users can't add this line before instantiating pygame_gui.ui_manager.UIManager() because code that is using threads isn't effected by adding this line and it has to be in the source code of pygame_gui.

**Comment by MyreMylar** [comment]
Thanks for the report. 

I'd be curious to know what you are doing with `pygame_gui` away from the main thread - where you are presumably calling `pygame.init()`. Is this for file loading?

**Comment by MyreMylar** [comment]
I'm at a bit of a loss with this one as I'm not 100% sure what you were doing to trigger this error.

The font loading already runs on separate threads - that is built into pygame GUI by default; the actual drawing of the UI needs to be done on the same thread you initialise pygame and because the UIManager manage the UI drawing it needs to be on that thread too. 

I don't know how or why you are ending up in a situation where you are creating the UIManager on a different thread to that which you initialise pygame on.
