### ISSUE TITLE
Set on_click button as a property or on the creation of the button

### ISSUE THREAD

**Issue by Sxmourai** [MyreMylar/pygame_gui#389]
**Is your feature request related to a problem? Please describe.**
I building a game with some menus. I have a lot of buttons, and so I find it really hard to manage the clicks function on these buttons.

**Describe the solution you'd like**
It would be great to have a button.on_click, like the button.on_hovered, that we could set to have something a lot easier.

**Additional context**
I have an EventManager and a MenuManager, and it would be better if the event manager was separated from the menu manager.

Last thing: I found some errors in the library, by passing wrong inputs, you should instead create your own exceptions. (this isn't mandatory and can wait)

**Comment by MyreMylar** [comment]
Hello,

Generally the UI events are the best way to handle things happening with buttons (e.g. `UI_BUTTON_PRESSED`, `UI_BUTTON_START_PRESS`). I usually manage by passing the most recent events this loop over to any of my classes that need to care about events and then testing for the specific event they are interested in. If you don't want to use events for UI for some reason you will struggle with using the library because events are a fundamental part of how the UI objects communicate with each other and the rest of your application.

There is also a property on buttons called 'pressed' which will be true for one update loop after they are pressed - you can check this with the method `check_pressed()` as well


> Last thing: I found some errors in the library, by passing wrong inputs, you should instead create your own exceptions. (this isn't mandatory and can wait)

I am trying to cover the whole library with type hints which should give you typing errors in your IDE when the wrong data is passed to a class or function. There are some specific custom exceptions included for common errors as well.

**Comment by Sxmourai** [comment]
Okay, thanks for the quick reply !
I will try to use check_pressed... It's just gonna be a bit slower but it's fine.
I might try to implement the on_click if I really need to.
I'm currently working on a project, (which uses this library) but when I'm finished with that, I think I will try to contribute to this
great library.

**Comment by LondonClass** [comment]
> Hello,
> 
> Generally the UI events are the best way to handle things happening with buttons (e.g. , ). I usually manage by passing the most recent events this loop over to any of my classes that need to care about events and then testing for the specific event they are interested in. If you don't want to use events for UI for some reason you will struggle with using the library because events are a fundamental part of how the UI objects communicate with each other and the rest of your application.`UI_BUTTON_PRESSED``UI_BUTTON_START_PRESS`
> 
> There is also a property on buttons called 'pressed' which will be true for one update loop after they are pressed - you can check this with the method as well`check_pressed()`
> 
> > Last thing: I found some errors in the library, by passing wrong inputs, you should instead create your own exceptions. (this isn't mandatory and can wait)
> 
> I am trying to cover the whole library with type hints which should give you typing errors in your IDE when the wrong data is passed to a class or function. There are some specific custom exceptions included for common errors as well.



> Hello,
> 
> Generally the UI events are the best way to handle things happening with buttons (e.g. , ). I usually manage by passing the most recent events this loop over to any of my classes that need to care about events and then testing for the specific event they are interested in. If you don't want to use events for UI for some reason you will struggle with using the library because events are a fundamental part of how the UI objects communicate with each other and the rest of your application.`UI_BUTTON_PRESSED``UI_BUTTON_START_PRESS`
> 
> There is also a property on buttons called 'pressed' which will be true for one update loop after they are pressed - you can check this with the method as well`check_pressed()`
> 
> > Last thing: I found some errors in the library, by passing wrong inputs, you should instead create your own exceptions. (this isn't mandatory and can wait)
> 
> I am trying to cover the whole library with type hints which should give you typing errors in your IDE when the wrong data is passed to a class or function. There are some specific custom exceptions included for common errors as well.

But I still hope that the button has an on_click like attribute. Users can pass in a function to this attribute, which is automatically called every time the button is clicked.
Since the process_event method of the button will be automatically called, all you need to do is add code to it and call the on_click variable when the button is detected as clicked.
In current situation, it may be difficult for the program to obtain an instance of the button for detecting events. If the button simply calls a certain function when pressed, it can be omitted from writing logic in UI events. The program will become simpler.

I hope the on_click attribute of the button can be passed in and saved when the button is created, and automatically called when click.

**Comment by LondonClass** [comment]
May I ask if # 493 has solved your problem?

**Comment by Sxmourai** [comment]
Hum I'm not too much into python now 🤣
But I think that's what I was looking for...
