### ISSUE TITLE
Cascading visibility control?

### ISSUE THREAD

**Issue by robclewley** [MyreMylar/pygame_gui#402]
**Is your feature request related to a problem? Please describe.**

I'm fairly new to this lib, so please correct me if I'm missing how to get this functionality already, but I can't find it in the documentation or the code. I'd like to be able to control visibility of whole groups based on containment, and I find the current behavior confusing.

Based on my read of your examples, I add elements to a UIContainer by first creating the container, then create the member elements while setting `container=<parent>` in their init call.

Then, I set the container's `visible` attribute to 0 prior to running the main loop, and all those elements are not visible, as expected.

But when I later set the container's `visible` to 1, nothing appears (the container itself doesn't have graphics), and I can confirm the member elements still have their `visible` value of 0.

**Describe the solution you'd like**

I'd like either a change to `visible` on a parent container to automatically cascade to its members, or for there to be a different method to force that to happen if it's not desirable for that to be the default. If there's a better way to be doing this with the existing code, I'd love to see a whole section added to the docs about organizing containers and controlling their visibility dynamically at run time.

**Describe alternatives you've considered**

Right now, I have to manually organize which things belong to what and set visibility individually using a function.

**Additional context**

I do see a `add_element` method which is not used in the examples, nor is it documented.

I'd be willing to make a PR for the new functionality if it's desirable.

**Comment by MyreMylar** [comment]
You want to use the show() and hide() methods of the container.

The API documentation is currently not being generated for an unknown
reason but there is underlying documentation for these functions.

Thanks for the report! I think there are areas of the library where it
could make more use of properties as public attributes instead of methods.
My background was more old school C/Java before moving to python so a fair
bit of the library doesn't use python exclusive features like this from my
coding style influence.

Though in this case I didn't write the hide() and show() functionality.
