### ISSUE TITLE
Can't change text size in UITextBox

### ISSUE THREAD

**Issue by A6086X** [MyreMylar/pygame_gui#468]
**Describe the bug**
Unable to change text size through the following code
text = "<font face='Arial' size=4.5> Hello World! </font>"
ui_text_box = pygame_gui.elements.ui_text_box.UITextBox(html_text=text,relative_rect=pygame.Rect((0,0),(200,200)),manager=manager)

**To Reproduce**
See example files attached.
[test.zip](https://github.com/MyreMylar/pygame_gui/files/11945019/test.zip)

**Expected behaviour**
Changing the "size" in the<font>label can change the text size

**Screenshots**
see sample files.

**Platform and software (please complete the following information):**
 - OS: Windows11
 - Pygame GUI version  0.6.9
 - Pygame version 2.5.0

**Additional context**
N/A

**Comment by MyreMylar** [comment]
Hello,

This caused by two things:

1. For some reason there isn't a warning message when the GUI library just can't find a font face during HTML parsed font loading.
2. Pygame GUI doesn't use the SystemFont style loading of pygame-ce at the moment, it actually uses the slightly weird freetype font submodule, which is incompatible with the standard font module that SystemFont co-exists with. I'm trying to switch back over to font as, in the time since I built the font rendering code, the font submodule has improved while freetype font has stalled. Long story short, right now you need to let pygame GUI know when you are defining a new font face alias that you are going to use in html text later. e.g.:

```python
import pygame_gui
import pygame
import sys
pygame.init()
clock = pygame.time.Clock()
clock_FPS = 25

screen = pygame.display.set_mode([800, 800])
manager = pygame_gui.UIManager((800, 800))

manager.add_font_paths("Arial",
                       "C:/Windows/fonts/arial.ttf")

text = "<font face='Arial' size=7> Hello World! </font>"
ui_text_box = pygame_gui.elements.ui_text_box.UITextBox(html_text=text,relative_rect=pygame.Rect((0,0),(500,200)),manager=manager)


while True:
    manager.update(clock.tick(clock_FPS)/1000)
    
    for event in pygame.event.get():
        #GUI事件传入
        manager.process_events(event)
        #退出
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
    
    screen.fill((255,255,255))
    manager.draw_ui(screen)  
    pygame.display.update()
```

**Comment by MyreMylar** [comment]
I've just switched back over to pygame.font so I may now be able to get the SystemFont module to step in as a fallback when it can't find a font name.
