### ISSUE TITLE
Adding Theming Parameters for UIContainer and UIScrollableContainer

### ISSUE THREAD

**Issue by GimLala** [MyreMylar/pygame_gui#489]
They currently have no theming parameters.

**Describe the solution you'd like**
I'd like theming parameters like borders, background, shape and shadow to be added (similar to other `UIElements `like `UIPanel`s, etc.)

**Comment by chavi362** [comment]
hi @MyreMylar,
I think I would like to work on this!!!
Please tell me if you like that I do this.
And can you explain me on which files should I work and give me a basic gaudiness on how to do this?
Then please assign it to me
Best regards,
Chavi

**Comment by MyreMylar** [comment]
Hi,

I think, from the description, that you both want `UIPanel` or `UIWindow` for an element that has visible stuff to it. `UIContainer` is 'invisible' in that it doesn't draw anything as part of itself. `UIWindow` and `UIPanel` are both container type elements (built around `UIContainer`) that have visible/themeable stuff to them like borders, background shape and shadow, that is the main distinction.

If we added basic visible/themable stuff to `UIContainer` it would then just become a `UIPanel`. For the `UIScrollingContainer` - currently you can just add one inside of the existing default `UIContainer` for either `UIPanel of `UIWindow` if that makes sense. I have thought about adding an option to `UIPanel` and `UIWindow` so that they can start with a `UIScrollingContainer` - Or just making their default container a scrolling one, but haven't decided if that is a good idea or not yet.

Anyway, that is my current feeling - if there is something `UIContainer` is providing that `UIPanel` or `UIWindow` isn't I'd be curious to hear it.

**Comment by chavi362** [comment]
Hi @MyreMylar,

Thank you for providing your insights on the issue. I appreciate your consideration of the UIContainer, UIPanel, and UIWindow design aspects.

I understand your concerns about UIContainer potentially becoming too similar to UIPanel or UIWindow with visible and themable features. I'm eager to contribute and would like to work on a solution that aligns with the project's goals.

Could you explain me better what do you mean on your idea about adding an option to UIPanel and UIWindow to start with a UIScrollingContainer.
As a beginner in Python, I'm eager to learn and contribute to the project. If you could provide some guidance on which files I should focus on and offer a basic outline of how to approach this task, it would be immensely helpful.

Moreover, if you think this task might not be the best fit for a beginner, I would greatly appreciate your recommendations for another enhancement issue that aligns with my skill level. I'm here to learn and contribute to the project in a meaningful way.

Thank you for considering my interest, and I look forward to your guidance
Chavi362

**Comment by MyreMylar** [comment]
Hi Chavi262,

Above I was musing on whether it might be better to replace the current `UIContainer` in `UIPanel` with a `UIScrollingContainer`. If you have a look at line 97 of UIPanel:

https://github.com/MyreMylar/pygame_gui/blob/f1cedab82e8e70824cf374ebb7be7fc620bb8cd5/pygame_gui/elements/ui_panel.py#L97

You will see the Panel creates a `UIContainer` which is then used to store all the elements add to the panel. It's possible, but untested, we could just replace this with a `UIScrollingContainer`. If that works (and doesn't break anything) then that seems a reasonable starting point for enabling scrolling panels more generally.

At the minute a `UIScrollingContainer` only expands it's scrollable area when it is told to do so - however we could perhaps add an option (I'm thinking a parameter, defaulting to off, called `auto_expand` in the __init__ function) to make it automatically expand to contain any element added to it that is outside the current scrollable area.

If we added both these features and then set the auto expand to true for the `UIScrollingContainer` in the `UIPanel` then we might have some useful new functionality that is fairly easy to use and doesn't break how anything currently works

Though all this is just some general musing, it is possible there will be issues and snags along the way.

If all that sounds too complicated, then I've also just added a documentation improvement issue.

**Comment by GimLala** [comment]
Hello MyreMylar,
I actually was working on the same thing where you can automatically resize the scrolling container (and even the normal container) when you add elements and when you remove them, and you are right, they cause a lot of problems because of anchoring. But I have managed to make them work and soon will make a pull request with the suggested changes
