### ISSUE TITLE
Add default 0 sized scrollbars to UIScrollableContainer

### ISSUE THREAD

**Issue by GimLala** [MyreMylar/pygame_gui#497]
**Is your feature request related to a problem? Please describe.**
Whenever I want to resize and position my elements in relation to the `UIVerticalScrollBar` to the right, or much less commonly, `UIHorizontalScrollBar` to the bottom at the time of creation of my container, before it has those scrollbars, I am unable to do so.

**Describe the solution you'd like**
Instead of having `None` as the `vert_scroll_bar` and `horiz_scroll_bar`, when initialised, I think the `UIScrollingContainer` should have the appropriate scrollbars initialised with 0 width and height which would make it easy to anchor the elements in relation to them so that even when the height of the `scrollable_container` exceeds the `_root_container` The elements automatically re-position and resize according to it.

**Comment by LondonClass** [comment]
Perhaps two variables should be added to control whether the container has a scrollbar.

**Comment by MyreMylar** [comment]
I think what was actually happening here is that:

1.  UIElements were being placed inside the `.scrollable_container` of a `UIScrollingContainer`.
2.  Then when a scroll bar is added to the right hand side - because content has extended below the bottom - the `._view_container` contracts to make room for the scroll bar.
3. However the scrolling container was staying the same size as before so it's right edge would now have overlapped the view container making no accounting for the appearance of the scroll bar.

I think probably what should happen is that if a container is specifically constrained to scroll only in one axis then the scrolling container should narrow along that axis when the view container does. If it is unconstrained in both axis - then I guess it should stay as it is now.

Does that make sense?
