### ISSUE TITLE
UIButton.set_dimensions() method does not support dynamic sizes

### ISSUE THREAD

**Issue by GimLala** [MyreMylar/pygame_gui#498]
**Describe the bug**
The method cannot be called with either of the arguments as -1 because it has an if condition which does not allow for negative values. This means that once a button has been initialised, it is impossible for it to be resized if it dynamically resizes either horizontally or vertically. I suspect this is also the case for other dynamically sized elements

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialise a button with any size
2. Try to resize button usnig UIButton.set_dimensions(-1, 200) # Or any size where atleast one of the dimensions is -1
3. You'll see that the button has either disappeared or appears in an unexpected size

**Expected behaviour**
When a button is resized with -1 in any of the sizes, it should be able to resize appropriately. Perhaps if the button didn't already have dynamic sizing, it should be able to switch from dynamically sized to normally sized and vice versa. This should be changed in the UIElement function in the if statement.

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.8
 - Pygame version 2.1

If there are any questions, please feel free to ask and I will do my best to clarify

**Comment by LondonClass** [comment]
To be honest, this thing is a little complicated. Because not only buttons have a dynamic attribute, but also the drawable_shape below them has a dynamic attribute. As far as I know, button does not have a method to switch whether it is dynamic or not.

I think it can be solved. Modify the dynamic properties of self and drawable_shape by detecting whether -1 is passed in. Then call the redraw of drawable_shape to solve the problem. I just don't know what impact it will bring.

**Comment by GimLala** [comment]
I might fix that myself if I am free, eventually
