### ISSUE TITLE
Elements not in container's focus set by default

### ISSUE THREAD

**Issue by GimLala** [MyreMylar/pygame_gui#527]
**Describe the bug**
The elements which are added to a container do not get added to the container's focus set. I think it would be better if it did add it to the focus set, atleast in `UIScrollingContainers `so that the scrollbars would scroll when any of the elements are in focus. Perhaps some checks would be needed to ensure that elements which have their own scroll bars are not added and also if the container is the root container then elements should not be added as then every element would become inter-connected.

Perhaps this will also allow for keyboard inputs like pressing Tab to navigate to different elements? That could be very useful in the UIForm

**Comment by MyreMylar** [comment]
I think generally you want mouse focus to be on the inner most thing that accepts the type of input - e,g, if you are mouse wheel scrolling you want scroll the inner most thing you are hovering in terms of containers. 

You could test this by sticking a text box with a scrollbar inside of a scrollable area, inside of a scrollable area and check it works how you'd like.

Keyboard focus is a different concept I think, 'mouse focus' is determined by where the mouse is hovering, but keyboard focus is only engaged after a mouse click. Tab focus is definitely more related to keyboard focus than mouse focus but is more broad because you can tab to things you can't type text into. Tab focus is also I think identical with 'trackpad focus' on a console controller, while mouse focus matches better with controller analogue sticks.

**Comment by GimLala** [comment]
Yeah, you're right, these are each a bit different, but those are all cool features to properly implement to make the games and any application in general feel more responsive

**Comment by MyreMylar** [comment]
Related #450
