### ISSUE TITLE
Calling hide() on a hidden button generates a spurious unhover event

### ISSUE THREAD

**Issue by retsyx** [MyreMylar/pygame_gui#610]
**Describe the bug**
Hiding a button unconditionally generates an unhover event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Call hide() on a button
2. Call hide() again
3. See unhover event from button

**Expected behaviour**
Calling hide() on an already hidden button should not generate any incorrect events.

**Screenshots**

N/A

**Platform and software (please complete the following information):**
 - OS: Linux
 - Pygame GUI version - latest
 - Pygame version - latest

**Additional context**

This may apply to other UI elements. Not tested.

This bug forces checking visibility on UI elements before calling hide() to avoid triggering these incorrect events.

**Comment by rbaltrusch** [comment]
Hi @MyreMylar, could you assign me this issue and review my PR? It should fix this issue for all widgets in the code base. 

However, in my opinion, there is a related and more complicated issue here that I am not fixing with this PR that might need additional work: the method `on_unhovered` can get called without the `hovered` state actually being set (due to that state being independently handled outside of that method), which partially leads to the issue described here. It would make more sense to not be able to unhover if already unhovered.
