### ISSUE TITLE
Images in text

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#62]
**Is your feature request related to a problem? Please describe.**
Unabel to show images as part of a text box, and in line with text. 

**Describe the solution you'd like**
HTML tag for an image allowing for images to be rendered in line with text. 

**Additional context**
https://i.imgur.com/cDG9RDw.png

**Comment by MyreMylar** [comment]
Definitely something I'd like to support, but will require a lot of refactoring in the text code which I'm trying to avoid touching much until version 0.6.0.

**Comment by Snayff** [comment]
Have you had any luck on this? Is it looking likely for 0.6.0? I'm debating whether to update some of my UI now or wait for the next update.

**Comment by MyreMylar** [comment]
There has been progress on the 0.6.0 branch you can see over here:

https://github.com/MyreMylar/pygame_gui/tree/version_060

So far, I haven't put images or the `<img>` tag in as a feature yet - but I have added support for floating rectangles in text layouts which are intended for the purpose of adding images in text. Slow and steady progress 👍 

Things have been somewhat delayed because I've been doing some work to try and get pygame 2.0 out the door finally so we don't have to deal with development versions anymore.

**Comment by Snayff** [comment]
Exciting! Certainly wasn't trying to chase you, buddy. :)

**Comment by MyreMylar** [comment]
While this is done there is still a bug in it somewhere I need to track down.

 I'll open a new issue.
