### ISSUE TITLE
Text Box after being killed and redrawn, displays text from the beginning.

### ISSUE THREAD

**Issue by St3veR0nin** [MyreMylar/pygame_gui#69]
Basically, i don't know if this is a bug, but when i try to kill() and create again the text box after some text has been written. Let's say that the scroll bar is pointing on the last bottom part of the text. The text box after the redraw display the initial part of the text. 

**To Reproduce**
Steps to reproduce the behaviour:
1. create a text box with a text entry
2. every time we insert text on the text entry and press enter, we kill() the text box if it is not None, then we redraw it with the new added text.
3. If we insert text when the scroll bar is pointing on the last part of the text, and press enter, the scroll bar is now pointing to the initial part of the text.

**Expected behaviour**
What i want is the scroll bar of the text box to point to the last part of the text when i redraw the text box.

**Platform**
 - OS: Windows 8.1
 - Pygame GUI version 0.4.2
 - Pygame version 2.0.0.dev6

**Comment by MyreMylar** [comment]
I think this will be best resolved by something like an 'add_text()' method that explicitly adds text at the end of the text box without deleting and recreating it, thus also allowing us to preserve the current position in the box and fixing a few other minor bugs with the text at the same time.

Editing fancily formatted text in real-time is somewhat tricky (just because all the formatting (colours, styles & word wrapping) takes a while to calculate and longer the more of each you have), Which is why I've been avoiding it - but I suspect with a bit of refactoring it will be much more possible to add text onto the end of already formatted text without needing to reformat the whole lot at once, making it easier to do things like logs with the Text Boxes.

At some point I may also create a properly editable text block that strips out all the fancy formatting display, much like the one I am typing this into right now.

It's an involved bit of work though so I may have to leave it until version 0.6.0.
