### ISSUE TITLE
Dropdown Max Options & Scrolling

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#73]
**Is your feature request related to a problem? Please describe.**
It is easy for drop downs to go off the screen or be excessively long, if there are several options. 

**Describe the solution you'd like**
Have a max_options_shown parameter that limits the amount of options shown in the drop down. If the amount of options exceeds the amount shown then add a scroll bar to allow scrolling of the options.

**Comment by MyreMylar** [comment]
There will be a version of this added in 0.5.0, essentially drop down menus have been changed to use the new 'selection list' element when expanded - which includes a scroll bar when the amount of elements added exceeds the display space for the selection list.

Rather than a number of elements I allow you to set a maximum pixel height for the expanding part of the menu, which defaults to the boundaries of the container the drop down is in (so it shouldn't go off the screen or outside a window the drop down is in).

It'll probably have lots of fun new bugs due to all the big changes but I think it should shake out to be simpler in the long run with less repeated code for similar effects all over the code base.

I'll close this request when 0.5.0 releases and then we can handle any more specific issues or bugs with it in new reports.
