### ISSUE TITLE
Creating 100+ buttons in a frame has got slower since version 0.41

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#91]
**Describe the bug**
Upgraded to latest version and amended references to UIWindow as well as updating the element id args. No other changes in code. After the upgrade getting consistently ~10 fps less.

**Expected behaviour**
Same performance as before. 

**Platform and software (please complete the following information):**
 - OS: Windows 10 64bit
 - Pygame GUI version: 0.5.1
 - Pygame version: 2.0.0dev6

**Comment by MyreMylar** [comment]
Hmm, that's not pleasing.

What element's are you using a lot of? 

My overnight thought was that the UIImage class was switched to using convert_alpha() on incoming images so they would work inside of resizable/scrolling windows but that might make the blitting of each a bit slower, so if they were being heavily used....

Otherwise it was mostly the windows that got changed a lot, but there could easily be a small thing somewhere I missed.

I'm currently working on a sort of 5.5 to support work I'm doing on a Paint program so if we can figure it out perhaps we can get a fix into that.

**Comment by Snayff** [comment]
I have 5 UIWindow's which enclose a total of 1 textbox and 6 buttons. I am planning to refactor the lot as they dont need to be windows anymore so that might help, but I wanted to raise it with you in case it is something underlying. 

Looking at my profiling it's the draw code here (https://github.com/Snayff/notquiteparadise/blob/develop/scripts/engine/ui/manager.py) that has spiked, but that doesnt tell us much, unfortunately.

**Comment by MyreMylar** [comment]
I think I just found one of the biggest performance blocks in your code. Here:

    def _draw_debug(self):
        values = debug.get_visible_values()
        y = 10

        for value in values:
            text, rect = Font().debug.render(value, (255,255,255))
            self._main_surface.blit(text, (0, y))
            y += 10

the call to Font() here is loading the fonts every loop of your game. If you instead move the call to Font() up into your _UIManager __init__ method, store the loaded fonts in a variable like 'self.fonts' and then do:

    def _draw_debug(self):
        values = debug.get_visible_values()
        y = 10

        for value in values:
            text, rect = self.fonts.debug.font.render(value, (255,255,255))
            self._main_surface.blit(text, (0, y))
            y += 10

I see a large jump in FPS. There is still some slowdown coming from the main map menu, but at least we can hit 60FPS-ish  with the other windows open now.

**Comment by Snayff** [comment]
That's what I get for slapping together some debug code whilst doing something else! Thank you. In my current branch I have actually removed the call to `Font()` from that method and whilst the base fps is nearly 60 the fps when you move (arrow keys) still drops really low - ~10-15 fps **total**, which is only since the upgrade. I might have said already but I am planning to redo all of the GUI, especially the camera, so it will be interesting to see where we end up after that. 

I really appreciate your help on this, MyreMylar.

**Comment by MyreMylar** [comment]
Your spike on moving is where you create 150 buttons each time you move. In this bit of code here:

    def update_grid(self):
        """
        Update the tile grid to only have options in line with the tiles set OR the overlay
        """
        # clear existing grid tiles
        #self.grid.clear()

        manager = self.ui_manager
        start_col = self.start_tile_col
        start_row = self.start_tile_row

        if self.is_overlay_visible:
            if self.player_tile:
                player_tile_x = self.player_tile.x
                player_tile_y = self.player_tile.y
            else:
                player_tile_x = 0
                player_tile_y = 0

            directions = self.overlay_directions

            # draw the overlay
            for direction in directions:
                offset_tile_x, offset_tile_y = direction
                x = ((player_tile_x + offset_tile_x) - start_col) * TILE_SIZE
                y = ((player_tile_y + offset_tile_y) - start_row) * TILE_SIZE
                tile_rect = Rect(x, y, TILE_SIZE, TILE_SIZE)

                # get current row and col
                if x == 0:
                    tile_x = 0
                else:
                    tile_x = max(0, int(x / TILE_SIZE))
                if y == 0:
                    tile_y = 0
                else:
                    tile_y = max(0, int(y / TILE_SIZE))

                tile = UIButton(relative_rect=tile_rect, manager=manager, text="", container=self.grid,
                                parent_element=self.grid, object_id=f"#tile{tile_x},{tile_y}")
        else:
            tiles = self.tiles

            # create a grid for the tiles needed
            for tile in tiles:
                x = (tile.x - start_col) * TILE_SIZE
                y = (tile.y - start_row) * TILE_SIZE
                tile_rect = Rect(x, y, TILE_SIZE, TILE_SIZE)

                # get current row and col
                if x == 0:
                    tile_x = 0
                else:
                    tile_x = max(0, int(x / TILE_SIZE))
                if y == 0:
                    tile_y = 0
                else:
                    tile_y = max(0, int(y / TILE_SIZE))

                tile = UIButton(relative_rect=tile_rect,
                                manager=manager,
                                text="",
                                container=self.grid,
                                parent_element=self.grid,
                                object_id=f"#tile{tile_x},{tile_y}")

I'd suggest instead keeping the buttons around (probably in a 2D list/array like structure?) and making changes to them in place instead as that will likely be a lot faster that deleting and recreating all of them at once each time you move. Commenting out the grid function removes the FPS spike as far as I can tell. 

I am surprised it was able to run before though.

**Comment by MyreMylar** [comment]
> It sounds silly when you say it like that! Haha! How did you pinpoint the
> problem? I'm interested to know so that I can check for myself next time.

I stuck a few debugging breakpoints around some likely spots (stuff with UI code in them, since that was what seems to have triggered the change) that also weren't hit in normal running - then I pressed an arrow key and if any of the breakpoints got hit I tried commenting out that chunk of code and rerunning it to see if it was faster. 

I also tried working out how logically how your movement code worked first, but I got lost somewhere in the tangle of event listeners.

> Are there some cases when it's best to delete and recreate and others when
> it's best to amend? I know you suggested before to delete a text box and
> recreate it with the new text, rather than updating the text. (Although an
> update text method might be quite useful to prevent that need)

Basically it's generally better to not recreate stuff and just move it around, unless what you want to do isn't supported by the element. I think if its just moving whole UI elements about (changing their position or dimensions) then right now pretty much every UI element can do that. Support for other operations is patchy, you can do some things, like changing the text on a button but not others like adding a line of text on the end of a text box. In cases where there is no option, recreating can be a decent stop gap but it'll generally involve kicking everything that makes up the element out of memory and then putting it all back in again so is usually slower.

> I still find it odd that the performance changed after the upgrade but I starting to think it is 
> related rather than the actual cause.

Yeah, I changed a lot of stuff in the 5.0 batch of changes, and while I have tests and examples it's sort of inevitable that some things are going to end up behaving slightly differently. 

Poking at my performance examples it looks like creating large amounts of UIElements in a frame (100+) has got about twice as slow as 0.42, but performance for creating a smaller number of elements in a frame (50ish) that I was testing for before has remained pretty much unchanged between versions. Not sure why that is, or if it is even fixable without undoing other improvements, but at least I have an angle to investigate now.

**Comment by MyreMylar** [comment]
Just gonna re-open this to remind me to look at it in the future, though I think its probably lower priority now.

**Comment by MyreMylar** [comment]
Have had a chance to look at this now with the profiler and was able to make a few optimisation changes to bring things back to roughly the same speed as 0.4.1 - without any loss of functionality.

Has resulted in changing a few minor bits of the interface to do with getting theming parameters though.

These changes will appear in the next release, whenever that turns out to be (Or you can get them from the [optimisation/cleanup branch](https://github.com/MyreMylar/pygame_gui/tree/code-cleanup-optimisation) I am currently tinkering in).

**Comment by Snayff** [comment]
That's fantastic, nice work, mate!
