### ISSUE TITLE
Path from json file

### ISSUE THREAD

**Issue by kildirian** [MyreMylar/pygame_gui#96]
Hi,
The paths set in the json file are relative to the main.
Why they are not relative to the json file ?
Indeed, I have several file in my game. If a want to test just a particular class using the
```
if __name__ == '__main__':
    pygame.init() 
    ...
```
I can not use the same json file since the path of my font or images are relative to other main file.
Is there a way to do it ?

**Comment by MyreMylar** [comment]
There is no way right now to make the paths relative to anything other than the working directory of your code. Often you can manually set the working directory when running your program in an IDE, if this is the only consideration.

**Comment by MyreMylar** [comment]
There is now a new optional system for loading resource in the json file and outside of it using python's package/module syntax rather than file paths. This means you can load images from anywhere you can import their package from and should resolve your issue.

I have created [an example repository](https://github.com/MyreMylar/pygame_gui_multi_package_theming) to demonstrate how you can achieve this - so you can swap a whole theming including images by just changing which package you load the theme file from. Paths in the theme file are set like this:

For package 1, theme.json:

    "#button_1":
    {
        "images":
        {
            "normal_image": {
                "package": "package_one.images",
                "resource": "space_1.jpg"
            }
        }
    },

For package 2, theme.json:

    "#button_1":
    {
        "images":
        {
            "normal_image": {
                "package": "package_two.images",
                "resource": "space_4.jpg"
            }
        }
    },

including the name of the package. Everything should basically follow the rules of the python module import syntax from there I think. Then in the example project I swap between two themes with different images like this:

    manager = pygame_gui.UIManager((800, 600),
                               pygame_gui.PackageResource('package_two', 'theme.json'))


    manager = pygame_gui.UIManager((800, 600),
                               pygame_gui.PackageResource('package_one', 'theme.json'))

Hopefully using something like this will also solve your issue in a fairly tidy way?
